version: '3.8'

services:
  backend:
    build: ./backend
    # ports removed for security, access via Traefik only
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/judo_db
    depends_on:
      - db
    networks:
      - default
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.judo_backend.rule=Host(`judo-pesee.montlebon.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.judo_backend.priority=100"
      - "traefik.http.routers.judo_backend.entrypoints=websecure"
      - "traefik.http.routers.judo_backend.tls.certresolver=myresolver"
      - "traefik.http.routers.judo_backend.service=judo_backend_svc"
      - "traefik.http.services.judo_backend_svc.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.judo_backend.middlewares=api-strip"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    # Restore volume for hot-reload in dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.judo_frontend.rule=Host(`judo-pesee.montlebon.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.judo_frontend.entrypoints=websecure"
      - "traefik.http.routers.judo_frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.judo_frontend.service=judo_frontend_svc"
      - "traefik.http.services.judo_frontend_svc.loadbalancer.server.port=3000"
    networks:
      - default
      - traefik-network

  db:
    image: postgres:15
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=judo_db
    networks:
      - default

  webdb:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - default
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.webdb.rule=PathPrefix(`/webdb`)"
      - "traefik.http.routers.webdb.entrypoints=websecure"
      - "traefik.http.routers.webdb.tls.certresolver=myresolver"
      - "traefik.http.services.webdb.loadbalancer.server.port=8080"
      - "traefik.http.routers.webdb.middlewares=webdb-strip"
      - "traefik.http.middlewares.webdb-strip.stripprefix.prefixes=/webdb"

volumes:
  postgres_data:

networks:
  traefik-network:
    external: true
